services:
  frontend:
    container_name: fcvg-public-next
    image: ghcr.io/fvgtekken/fcvg-public-next:latest
    environment:
    DATABASE_URL: ${DATABASE_URL}
    ports:
      - 5000:5000
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - my-network-front   
      
networks:
  my-network-front:
    name: default-network-front
    driver: bridge