services:
  frontend:
    container_name: fcvg-public-next
    image: ghcr.io/fvgtekken/fcvg-public-next:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      NEXTAUTH_URL: "https://srv498956.hstgr.cloud"
      NEXTAUTH_INTERNAL_URL: "http://fcvg-public-next:5000"
    ports:
      - 5000:5000
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - my-network-next-front   
      - my-network-postgres
      
networks:
  my-network-next-front:
    external: true
    name: default-network-front
  my-network-postgres:
    external: true
    name: default-network-postgres  